name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 6 * * *'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
          OS_NAME: ${{ matrix.os }}
          TEST_INVALID_EMAIL_FORMAT: ${{ secrets.TEST_INVALID_EMAIL_FORMAT }}
          TEST_PASSWORD_FOR_INVALID_EMAIL_FORMAT: ${{ secrets.TEST_PASSWORD_FOR_INVALID_EMAIL_FORMAT }}
        
    - uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: playwright-report-${{ matrix.os }}
        path: playwright-report/
        retention-days: 30